### ISSUE TITLE
rundocker.sh won't run if 2FA enabled in Docker account.

### ISSUE THREAD

**Issue by RayAtRadix** [radixdlt/radixdlt#8]
If 2FA is enabled on your docker account, then the command line will need an access token supplied when it is run. 

So if you run ```rundocker.sh``` it'll fail with a permissions error.

Not a showstopper by any means; just thought I'd mention it.

**Comment by cbisaillon** [comment]
Can't you use the token as your password?

**Comment by RayAtRadix** [comment]
I tried tacking the token on the end of the script call, but that didn't seem to work. I'll play around with it some more.

**Comment by cbisaillon** [comment]
Can show use the error and more explanation ? I use 2FA and I am able to run `rundocker.sh`

**Comment by RayAtRadix** [comment]
Can't get it to do it again, so I'm going to put this one down to user error. 🤦🏾‍♂️
